/**
 * CENTRAL CONFIGURATION FILE
 * =========================================================================
 * Ubah semua data profil, tautan media sosial, marketplace, donasi, portofolio,
 * aplikasi premium, layanan komisi, dan playlist musik di sini dengan mudah!
 * =========================================================================
 */

export const siteConfig = {
  // --- IDENTITAS KREATOR / BRAND ---
  profile: {
    name: "Raihan Salman Alfarisy",
    brandName: "Rasfalz Studio",
    logoLightUrl: "https://files.catbox.moe/stbl4b.png", // Link URL Logo Wordmark Light Mode
    logoDarkUrl: "https://files.catbox.moe/27zr11.png",  // Link URL Logo Wordmark Dark Mode
    logoUrl: "https://files.catbox.moe/lmo2re.jpeg",      // Default Logo Fallback
    iconUrl: "https://files.catbox.moe/7lrmbf.jpeg",      // Icon Gambar / Favicon & Link Card
    role: "Motion & Graphic Designer",
    tagline: "Creative & Energy",
    shortBio: "Halo semuanya, kenalin namaku Raihan Salman Alfarisy, atau biasa dipanggil Raihan/Rasfalz. Saya adalah konten kreator yang bergerak di bidang desain grafis, penyuntingan video, dan fotografi. Saya bergabung dengan komunitas Mletre Unit, Glide Community, Our Creavity Community, Key Frame, Project Z1, Cingire Team, dan Visual Seven. Saya juga merupakan pendiri Matrix Team X Project FXZ. Jika ada pertanyaan, silakan hubungi saya. Terima kasih.",
    fullBio: `Halo, nama saya Raihan Salman Alfarisy atau lebih dikenal sebagai Rasfalz. Saya seorang desainer grafis dan media seperti, desain grafis, videografi, motion grafis, dan fotografi.

'Rasfalz' adalah identitas kreator konten asal Indonesia yang menyajikan karya editing serta kreativitas yang memikat audiens. Nama "Rasfalz" diambil dari nama lengkap saya, Raihan Salman Alfarisy, yang kemudian disingkat menjadi Rasfalz. Kalian dapat menemukan akunku di berbagai platform media sosial populer seperti TikTok, YouTube, Facebook, dan Instagram.

Rasfalz memulai kiprahnya pada Juli 2021; sebelumnya saya menggunakan nama 'Raihan AM' dengan konten bertema Jedag-Jedug, namun kini saya mulai merambah ke konten fotografi, motion graphics, GFX (Poster Anime), desain grafis, dan video AMV.

Saya telah membuat konten semacam ini selama beberapa tahun, tepatnya sejak 2016 hingga sekarang. Pada tahun 2016, aplikasi yang saya gunakan antara lain Kinemaster, Pixellab, Picsay, dan PicsArt. Namun, sejak 2021 hingga saat ini, saya menggunakan aplikasi editing seperti Alight Motion, CapCut, Photoshop, Illustrator, After Effects, Figma, Blender, dan Pixellab.

Kenapa saya membuat konten seperti itu? Karena di era saat ini, saya melihat banyak orang mengunggah video keren entah animasi atau desain grafis di media sosial. Saya pun mulai mencobanya setelah menonton tutorial di YouTube, hingga akhirnya saya menyadari adanya bakat terpendam dalam diri saya. Itulah alasan saya membuat konten semacam ini.

Demikian penjelasan singkat mengenai diri saya. Jika Anda ingin mengetahui lebih lanjut, silakan kirim pesan langsung (DM) atau hubungi saya. Sekian dan terima kasih.`,
    avatar: "https://files.catbox.moe/ke3ye3.jpg",
    location: "Sidoarjo, Jawa Timur, Indonesia (GMT+7)",
    status: "🟢 Paid Edit (Tergantung Mood)",
    experienceYears: "10+",
    projectsCompleted: "500+",
    happyClients: "100+",
    rating: "4.8/5.0",
    email: "raihanalfarisy354@gmail.com",
    cvUrl: "https://drive.google.com/file/d/1WCW7GBNgD8fTE4eE0Ecg-xU8GeqFVF4m/view?usp=sharing", // Link Google Drive CV Documentment
    cvDocument: {
      title: "Curriculum Vitae (CV) — Raihan Salman Alfarisy",
      subtitle: "Motion Designer • Graphic Designer • Video Editor",
      badge: "Official Resume 2026",
      format: "PDF Document (Interactive)",
      fileSize: "1,6 MB",
      lastUpdated: "September 2026",
      version: "v2.0 (Verified Edition)",
      driveUrl: "https://drive.google.com/file/d/1WCW7GBNgD8fTE4eE0Ecg-xU8GeqFVF4m/view?usp=sharing",
      status: "Verified by Rasfalz Studio",
      highlights: [
        "10+ Tahun Pengalaman Desain Grafis, Animasi & Video",
        "500+ Proyek Kreatif Visual Selesai & Berbayar",
        "Expertise: Alight Motion, Adobe Illustrator, Adobe Photoshop, Figma, CapCut, Canva.",
        "Track Record Kolaborasi Bersama Klien & Komunitas Digital",
      ],
      description: "Dokumen resmi Curriculum Vitae (CV) lengkap Raihan Salman Alfarisy. Memuat riwayat kerja profesional, keahlian teknis perangkat lunak, daftar proyek komersial, dan kontak resmi.",
    },
  },

  // --- TAUTAN KONTAK UTAMA (WhatsApp & Telegram) ---
  contact: {
    whatsappNumber: "6288803293497",
    whatsappUrl: "https://wa.me/6288803293497?text=Halo%20Raihan%2C%20saya%20tertarik%20untuk%20berkolaborasi%20atau%20order%20commission.",
    telegramUsername: "alwaysraihan",
    telegramUrl: "https://t.me/alwaysraihan",
    email: "mailto:raihanalfarisy354@gmail.com",
  },

  // --- MEDIA SOSIAL & PORTOFOLIO EKSTERNAL ---
  socials: {
    instagram: {
      name: "Instagram",
      handle: "@rasfalz.std",
      url: "https://instagram.com/rasfalz.std",
      description: "Akun Pribadi, Portfolio, dan Konten Kreatif Visual.",
      accent: "#E1306C",
    },
    tiktok: {
      name: "TikTok",
      handle: "@rasfalz.std",
      url: "https://tiktok.com/@rasfalz.std",
      description: "Portofolio Motion Designer & Graphic Designer, serta konten kreatif visual pendek.",
      accent: "#00F2FE",
    },
    youtube: {
      name: "YouTube",
      handle: "Raihan (Rasfalz Studio)",
      url: "https://www.youtube.com/@rasfalz-std",
      description: "Portofolio Motion Designer & Video Editor, serta konten kreatif visual panjang.",
      accent: "#FF0000",
    },
    facebook: {
      name: "Facebook",
      handle: "Raihan Salman Alfarisy",
      url: "https://www.facebook.com/raihan.salmanalfarisy.397",
      description: "Halaman & Komunitas Kreatif di Facebook.",
      accent: "#1877F2",
    },
    telegram: {
      name: "Telegram",
      handle: "@alwaysraihan",
      url: "https://t.me/alwaysraihan",
      description: "Direct Chat & Diskusi Proyek Kreatif Cepat.",
      accent: "#229ED9",
    },
    github: {
      name: "Github",
      handle: "@farisganteng220",
      url: "https://github.com/farisganteng220",
      description: "Portofolio Basic Coding & Javascript",
      accent: "#6e5494",
    },
  },

  // --- EXTERNAL PORTFOLIO HUBS ---
  externalPortfolios: [
    {
      id: "ext-gallery",
      platform: "Visual Gallery & Desain Grafis",
      tag: "Aplikasi Gallery",
      description: "Buka aplikasi Galeri Visual untuk melihat portofolio berupa Desain Grafis, 3D Render Artworks, Behind the Scenes, dan Koleksi Visual Rasfalz Studio.",
      isInternalApp: true,
      appId: "gallery",
      icon: "Image",
      accent: "#FF9C0F",
    },
    {
      id: "ext-1",
      platform: "Portofolio Foriio First",
      tag: "Foriio",
      description: "Portofolio External Pertama, isinya berupa Motion Designer, Graphic Designer",
      url: "https://www.foriio.com/imnotraihan",
      icon: "Palette",
      accent: "#0052F5",
    },
    {
      id: "ext-2",
      platform: "Portofolio Foriio Second",
      tag: "Foriio",
      description: "Portofolio External Kedua, isinya berupa Motion Designer, Graphic Designer",
      url: "https://www.foriio.com/rasfalz-std",
      icon: "Layout",
      accent: "#FF9C0F",
    },
    {
      id: "ext-files",
      platform: "File Explorer & Cloud Storage",
      tag: "Aplikasi File Explorer",
      description: "Akses pusat File Explorer untuk melihat portofolio lainnya, folder Google Drive, preset LUTs sinematik, SFX, dan seluruh master project files.",
      isInternalApp: true,
      appId: "files",
      icon: "FolderTree",
      accent: "#10B981",
    },
  ],

  // --- KOMUNITAS (WhatsApp & Telegram: Group & Channel) ---
  communities: [
    {
      id: "comm-wa-group",
      type: "group",
      name: "Grup Komunitas WhatsApp",
      platform: "WhatsApp",
      badge: "Grup Diskusi",
      tagline: "Forum Interaktif Kreator",
      membersCount: "20+ Member Aktif",
      description: "Ruang diskusi interaktif untuk sesama editor & designer. Saling berbagi tips pengeditan cepat, bedah karya, tanya jawab software, dan feedback langsung dari Raihan.",
      url: "https://chat.whatsapp.com/EpISGAGyVio5GE3UAm1xyB?s=cl&p=a&mlu=4&ilr=4",
      adminWaUrl: "https://wa.me/6288803293497?text=Halo%20Raihan%2C%20saya%20tertarik%20untuk%20bergabung%20ke%20Grup%20WhatsApp%20Komunitas%20MatrixTeam",
      buttonText: "Gabung Grup WhatsApp",
      color: "#25D366",
      icon: "MessagesSquare",
      perks: [
        "Diskusi real-time dan feedback langsung",
        "Sharing tutorial editing eksklusif",
        "Akses mentahan & preset gratis",
        "Info promosi dan project",
      ],
    },
    {
      id: "comm-wa-channel",
      type: "channel",
      name: "Saluran WhatsApp Resmi",
      platform: "WhatsApp",
      badge: "Saluran Resmi",
      tagline: "Broadcast & Update Tercepat",
      membersCount: "20+ Pengikut",
      description: "Saluran siaran satu arah untuk mendapatkan rilis preset terbaru, pengumuman slot komisi, info diskon aplikasi premium, dan konten tanpa notifikasi berisik.",
      url: "https://whatsapp.com/channel/0029VamkyeL002T0wyDpA22d",
      buttonText: "Ikuti Saluran WhatsApp",
      color: "#25D366",
      icon: "Radio",
      perks: [
        "Pemberitahuan rilis karya & video baru",
        "Akses link preset & mentahan terpilih gratis",
        "Info komisi & penawaran spesial",
        "Bebas spam & notifikasi rapi satu arah",
      ],
    },
    {
      id: "comm-tg-channel",
      type: "channel",
      name: "Mentahan Raihan 3D",
      platform: "Telegram",
      badge: "Resource Hub",
      tagline: "Cloud Archive File Asli 4K",
      membersCount: "200+ Subscribers",
      description: "Cloud archive tercepat untuk download mentahan 3D, preset Alight Motion (XML/5MB), project file, dan materi aset grafis tanpa kompresi kualitas.",
      url: "https://t.me/mentahanraihan3d",
      buttonText: "Join Telegram Channel",
      color: "#229ED9",
      icon: "Send",
      perks: [
        "Mentahan & preset gratis kualitas original",
        "Project file Alight Motion",
        "Info update paid edit, promosi, dan info lainnya",
        "Penyimpanan cloud cepat tanpa batas waktu",
      ],
    },
    {
      id: "comm-tg-group",
      type: "group",
      name: "Grup Komunitas Telegram",
      platform: "Telegram",
      badge: "Grup Diskusi",
      tagline: "Komunitas Kreatif Telegram",
      membersCount: "10+ Member",
      description: "Forum obrolan bebas ukuran file besar, sharing file project mentahan, konsultasi teknis After Effects & Alight Motion, dan kolaborasi tim kreatif.",
      url: "https://t.me/chatraihan",
      buttonText: "Gabung Grup Telegram",
      color: "#229ED9",
      icon: "Users",
      perks: [
        "Kirim file project & aset ukuran besar tanpa batas",
        "Diskusi teknis editing dan bedah preset",
        "Koneksi sesama animator, editor & desainer grafis",
        "Sharing referensi aset & tips produktivitas",
      ],
    },
  ],

  // --- DONASI & DUKUNGAN (Trakteer, Saweria, QRIS) ---
  donations: [
    {
      id: "don-trakteer",
      name: "Trakteer.id",
      logoText: "Traktir Boba Ice",
      tagline: "Support karya & download reward konten eksklusif",
      url: "https://trakteer.id/raihan354",
      buttonText: "Support on Trakteer",
      color: "#be1e2d",
      unit: "1 Boba Ice = Rp 3.000",
      description: "Dukungan kamu membantu saya membuat lebih banyak preset gratis, video tutorial, dan upgrade perangkat",
    },
    {
      id: "don-saweria",
      name: "Saweria.co",
      logoText: "Live Stream / Direct Tip",
      tagline: "Dukungan instan via QRIS, GoPay, OVO, Dana, ShopeePay",
      url: "https://saweria.co/raihan354",
      buttonText: "Support on Saweria",
      color: "#FA9D24",
      unit: "Min. Rp 10.000",
      description: "Kirim pesan dukungan yang akan langsung muncul di notification bar website OS ini!",
    },
    {
      id: "don-sociabuzz",
      name: "SociaBuzz",
      logoText: "Donasi dan Dukungan Kreator",
      tagline: "Dukungan instan via QRIS, GoPay, OVO, Dana, ShopeePay",
      url: "https://sociabuzz.com/imnot_r4ihan354",
      buttonText: "Support on SociaBuzz",
      color: "#2A7C13",
      unit: "Min. Rp 10.000",
      description: "Jangan Lupa Donasi dan Dukung Kami ya!",
    },
    {
      id: "don-qris",
      name: "QRIS",
      logoText: "Donasi dan Sumbangan Pakai QRIS",
      tagline: "Dukungan instan via QRIS",
      url: "https://files.catbox.moe/0wygml.jpeg",
      buttonText: "Support on QRIS",
      color: "#2196F3",
      unit: "Bebas tanpa minimum",
      description: "Jangan Lupa scan dan bayar donasi seikhlasnya",
    }
  ],

  // --- ONLINE SHOP & MARKETPLACE HUBS ---
  onlineShopPlatforms: [
    {
      id: "shop-payhip",
      name: "Payhip Digital Store",
      type: "Global Digital Assets",
      badge: "Worldwide Instant Download",
      description: "Preset Alight Motion, Capcut, Canva, After Effect, dan Blender 3D",
      rating: "No Rating Xixi",
      url: "https://payhip.com/RaihanMLTR",
      color: "#2196F3",
      icon: "Store",
      itemsCount: "1+ Products",
    },
    {
      id: "shop-shopee",
      name: "Shopee Official Merchandise",
      type: "Product Digital & Random",
      badge: "Gratis Ongkir & COD",
      description: "Aplikasi Premium, Preset Editing, Barang Elektronik, dan Mentahan",
      rating: "5.0 (5+ Sales)",
      url: "https://shopee.co.id/raihansalman354",
      color: "#EE4D2D",
      icon: "Store",
      itemsCount: "16 Items",
    },
    {
      id: "shop-sociabuzz",
      name: "SociaBuzz Digital Store",
      type: "Product Digital & Preset",
      badge: "Local Digital Assets",
      description: "Aplikasi Premium, Preset Editing, dan Mentahan",
      rating: "No Rating Hehe",
      url: "https://sociabuzz.com/imnot_r4ihan354",
      color: "#408A71",
      icon: "Store",
      itemsCount: "1+ Items",
    },
  ],

  // --- APLIKASI PREMIUM (Marketplace / App Store) ---
  premiumApps: [
    {
      id: "app-1",
      name: "Alight Motion",
      category: "Video & Motion",
      subCategory: "Video Editing",
      duration: "1 Tahun",
      accountType: "Private / Request Email",
      discount: "96%",
      badge: "Popular",
      badgeColor: "#408175",
      price: "Rp 6.000",
      originalPrice: "Rp 149.000",
      rating: "4.8",
      downloads: "100+",
      icon: "Video",
      thumbnail: "https://files.catbox.moe/cscuk5.png",
      description: "Akun Alight Motion Premium Private Selama 1 Tahun",
      features: [
        "Bisa Request Email Pribadi ataupun Email dari kita",
        "Tidak Ada Watermark di Video",
        "Support 5MB keatas dan membuka efek premium",
        "100% Aman tidak ada kendala",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Alight%20Motion%20Premium%20selama%201%20Tahun.",
    },
    {
      id: "app-2",
      name: "CapCut",
      category: "Video & Motion",
      subCategory: "Video Editing",
      duration: "1 Bulan",
      accountType: "Private Full Garansi",
      discount: "79%",
      badge: "Best",
      badgeColor: "#303841",
      price: "Rp 30.000",
      originalPrice: "Rp 145.000",
      rating: "4.9",
      downloads: "20+",
      icon: "Pipette",
      thumbnail: "https://files.catbox.moe/pej2mj.png",
      description: "Akun Capcut Premium Selama 1 Bulan",
      features: [
        "Data Akun CapCut itu dari kita",
        "Membuka Fitur Premium dari Aplikasi Capcut",
        "Tanpa Watermark di Video",
        "100% Terjamin Aman",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20CapCut%20Premium%20selama%201%20bulan.",
    },
    {
      id: "app-3",
      name: "Canva Pro",
      category: "Graphic & Design",
      subCategory: "Design & Template",
      duration: "1 Tahun",
      accountType: "Member Pro Team",
      discount: "89%",
      badge: "Popular",
      badgeColor: "#723EC3",
      price: "Rp 10.000",
      originalPrice: "Rp 95.000",
      rating: "4.9",
      downloads: "50+",
      icon: "Box",
      thumbnail: "https://files.catbox.moe/rlm956.png",
      description: "Akun Canva Member Selama 1 Tahun",
      features: [
        "1000+ Elemen, Font, & Template Premium",
        "Tanpa Watermark",
        "Fitur Premium Terbuka",
        "100% Terjamin Aman",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Canva%20Member%20selama%201%20tahun.",
    },
    {
      id: "app-4",
      name: "Ibis Paint X",
      category: "Graphic & Design",
      subCategory: "Digital Art & Drawing",
      duration: "1 Tahun",
      accountType: "Sharing Akun Premium",
      discount: "92%",
      badge: "Best",
      badgeColor: "#2B2A2A",
      price: "Rp 15.000",
      originalPrice: "Rp 200.000",
      rating: "4.9",
      downloads: "50+",
      icon: "Music",
      thumbnail: "https://files.catbox.moe/act4th.png",
      description: "Akun Ibis Paint Sharing Selama 1 Tahun",
      features: [
        "Fitur Premium Terbuka",
        "Tanpa Iklan Sama Sekali",
        "Akunnya dari kita",
        "100% Terjamin Aman",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Ibis%20Paint%20selama%201%20tahun.",
    },
    {
      id: "app-5",
      name: "Wink Pro",
      category: "Tools Editing",
      subCategory: "Editing & Visual Effects",
      duration: "7 Hari",
      accountType: "Akun Pribadi",
      discount: "60%",
      badge: "Best Value",
      badgeColor: "#723EC3",
      price: "Rp 6.000",
      originalPrice: "Rp 15.000",
      rating: "4.9",
      downloads: "20+",
      icon: "Music",
      thumbnail: "https://files.catbox.moe/3p6vv3.png",
      description: "Akun Wink Pro selama 7 hari dengan harga super terjangkau.",
      features: [
        "Fitur Premium Lengkap",
        "Tanpa Watermark",
        "Hasil Video/Foto Full HD & 4K",
        "Unlimited Eksport",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Wink%20Pro%20selama%207%20hari.",
    },
    {
      id: "app-6",
      name: "Remini",
      category: "Tools Editing",
      subCategory: "Editing & Visual Effects",
      duration: "7 Hari",
      accountType: "Akun Buyer",
      discount: "60%",
      badge: "Best Value",
      badgeColor: "#723EC3",
      price: "Rp 6.000",
      originalPrice: "Rp 15.000",
      rating: "4.9",
      downloads: "20+",
      icon: "Music",
      thumbnail: "https://files.catbox.moe/dw7ciy.png",
      description: "Akun Remini Pro selama 7 hari dengan harga super terjangkau.",
      features: [
        "Fitur Premium Lengkap",
        "Tanpa Watermark",
        "Hasil Foto Full HD & 4K",
        "Unlimited Eksport",
      ],
      status: "Stok Ready",
      buyUrl: "https://wa.me/6288803293497?text=Halo%2C%20saya%20ingin%20membeli%20akun%20Remini%20Pro%20selama%207%20hari.",
    },
  ],

  // --- COMMISSION EDITING SERVICES ---
  commissionServices: [
    {
      id: "comm-graphic",
      title: "Graphic Design & Art Editing",
      category: "Photography & Creative Art",
      icon: "Image",
      startingPrice: "Rp 15.000 / foto",
      turnaround: "1 - 3 Hari Kerja",
      description: "Jasa Edit Foto dan Desain Grafis, seperti poster/flyer, GFX Anime, X Banner, Sosial Media Post, Thumbnail, Art Editing, Manipulation, dll",
      inclusions: [
        "Free Request Referensi dari kalian",
        "Revisi maksimal 3 kali",
        "Pengerjaannya Rapi dan Professional",
        "Output full-resolution JPEG, PNG, PDF, PSD, AI",
        "100% Terjamin Aman",
      ],
      popular: true,
    },
    {
      id: "comm-video",
      title: "Motion Graphic & Animation Editing",
      category: "Motion & Animation",
      icon: "Film",
      startingPrice: "Rp 35.000 / video",
      turnaround: "2 - 6 Hari Kerja",
      description: "Editing video motion graphic & animation, seperti typography animation, Motion Graphic(Mograph), AMV (Anime Music Video), PMV (Picture Music Video), dll",
      inclusions: [
        "Motion graphic dengan subtitle",
        "Free Request Referensi dari kalian",
        "Revisi maksimal 3 kali",
        "100% Terjamin Aman",
        "Output full-resolution MP4, MOV",
      ],
      popular: true,
    },
    {
      id: "comm-edu",
      title: "Video Education & Tugas Sekolah",
      category: "Video Editing",
      icon: "PenTool",
      startingPrice: "Rp 20.000 / menit",
      turnaround: "3 - 6 Hari Kerja",
      description: "Pembuatan video education & tugas sekolah dengan kualitas professional.",
      inclusions: [
        "Video education & tugas sekolah dengan kualitas professional",
        "Revisi maksimal 3 kali",
        "Pengerjaannya Rapi dan Professional",
        "Output full-resolution MP4, MOV",
      ],
      popular: false,
    },
  ],

  // --- PORTOFOLIO KARYA ---
  portfolioItems: [
    {
      id: "p1",
      title: "Nina Feast | Motion Graphic",
      category: "Motion Graphic",
      year: "2025",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/5eps5i.png",
      description: "Motion Graphic dengan elemen yang smooth dan synced dengan audio.",
      link: "https://www.tiktok.com/@rasfalz.std/video/7482299316728614162",
    },
    {
      id: "p2",
      title: "GFX March 7Th HSR | Graphic Design",
      category: "Graphic Design",
      year: "2024",
      tools: ["Adobe Photoshop"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/a5xpn8.webp",
      description: "Graphic Design dengan elemen yang gaya minimalis, modern, dan rapi.",
      link: "https://www.instagram.com/p/C8cJzhkvFOv/?img_index=2",
    },
    {
      id: "p3",
      title: "Dial Note ~ | Motion Graphic",
      category: "Motion Graphic",
      year: "2025",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/uzc6a5.png",
      description: "Motion Graphic dengan gaya brutalist dan elemen yang synced dengan audio.",
      link: "httpshttps://www.tiktok.com/@rasfalz.std/video/7558342526768336139",
    },
    {
      id: "p4",
      title: "Promotion Paid Edit | Video Editing",
      category: "Video Editing",
      year: "2025",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/7ck5rv.png",
      description: "Video Editing dengan gaya professional dan modern, supaya menarik para penonton. Cocok untuk video promosi, sosial media, dan lain-lain.",
      link: "https://www.tiktok.com/@rasfalz.std/video/7537876439534882056",
    },
    {
      id: "p5",
      title: "Kasih Aba Aba MLBB Edition | Motion Graphic",
      category: "Motion Graphic",
      year: "2025",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/74yc6s.png",
      description: "Motion Graphic dengan gaya MLBB dan elemen yang synced dengan audio.",
      link: "https://www.tiktok.com/@rasfalz.std/video/7524380687986691335",
    },
    {
      id: "p6",
      title: "Poster Idul Fitri Matrix Team | Graphic Designer",
      category: "Graphic Design",
      year: "2026",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/b8gikl.jpeg",
      description: "Poster Idul Fitri dengan elemen yang modern dan rapi.",
      link: "https://www.tiktok.com/@mxteam.ofc/photo/7619348718369672456",
    },
    {
      id: "p7",
      title: "Jedag Jedug K-On | Video Editing",
      category: "Video Editing",
      year: "2026",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/qg3xjh.png",
      description: "Video Editing dengan gaya Jedag Jedug dan elemen yang synced dengan audio.",
      link: "https://www.tiktok.com/@rasfalz.std/video/7616951534605061397",
    },
    {
      id: "p8",
      title: "Result Open Recruitment Mletre | Video Editing",
      category: "Video Editing",
      year: "2026",
      tools: ["Alight Motion"],
      client: "Mletre Im Here",
      image: "https://files.catbox.moe/lbv69e.png",
      description: "Video Editing dengan gaya professional dan modern, dan menampilkan elemen screenshot akun yang keterima Mletre, supaya menarik para penonton.",
      link: "https://drive.google.com/file/d/1L_40msFEaV-UhH0aNqKt3Or95ycWDH6m/view?usp=drive_link",
    },
    {
      id: "p9",
      title: "Tante My Bini | Motion Graphic",
      category: "Motion Graphic",
      year: "2025",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/ckwj2l.png",
      description: "Motion Graphic dengan gaya brutalist, elemen berbunga, dan tema/karakter yang sesuai dengan original karakter.",
      link: "https://www.tiktok.com/@rasfalz.std/video/7555650689599294776",
    },
    {
      id: "p10",
      title: "Jedag Jedug 3D Full Color Inframe gw sendiri | Video Editing",
      category: "Video Editing",
      year: "2025",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/yylppp.png",
      description: "Video Editing dengan gaya Jedag Jedug 3D dan elemen yang synced dengan audio.",
      link: "https://www.tiktok.com/@rasfalz.std/video/7493352563400641799",
    },
    {
      id: "p11",
      title: "GFX Hu-Tao | Graphic Design",
      category: "Graphic Design",
      year: "2024",
      tools: ["Adobe Illustrator"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/s7d8m5.jpeg",
      description: "Graphic Design dengan gaya clean, rapi, dan modern, supaya menarik para penonton.",
      link: "https://www.instagram.com/p/C2UnDl3vx6q/?img_index=2",
    },
    {
      id: "p12",
      title: "Separuh Aku Firefly HSR | AMV Editing",
      category: "Video Editing",
      year: "2024",
      tools: ["Alight Motion"],
      client: "Rasfalz Studio",
      image: "https://files.catbox.moe/pbpddz.png",
      description: "AMV Editing dengan gaya Sync dan elemen yang synced dengan audio.",
      link: "https://www.youtube.com/watch?v=fFH5Df24gCA",
    },
  ],

  // --- GALLERY ITEMS ---
  galleryItems: [
    {
      id: "g1",
      title: "Poster Cundamani Makaroni",
      category: "Graphic Design",
      image: "https://files.catbox.moe/bls3cr.jpeg",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g2",
      title: "GFX Wan Wan MLBB",
      category: "Graphic Design",
      image: "https://files.catbox.moe/hpwn52.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2025",
      aspect: "portrait",
    },
    {
      id: "g3",
      title: "Desain Jajanan Soesky (Tugas Sekolah)",
      category: "Graphic Design",
      image: "https://files.catbox.moe/dfhdzs.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "landscape",
    },
    {
      id: "g4",
      title: "Desain Jajanan Pastel!n",
      category: "Graphic Design",
      image: "https://files.catbox.moe/wmdgq5.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "Landscape",
    },
    {
      id: "g5",
      title: "Art My Character",
      category: "Graphic Design",
      image: "https://files.catbox.moe/k729go.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g6",
      title: "GFX Ganyu Genshin Impact",
      category: "Graphic Design",
      image: "https://files.catbox.moe/73frv9.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2023",
      aspect: "portrait",
    },
    {
      id: "g7",
      title: "Desain Aktivitas Magang",
      category: "Graphic Design",
      image: "https://files.catbox.moe/ns3qxm.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g8",
      title: "Desain Idul Adha Matrix Team",
      category: "Graphic Design",
      image: "https://files.catbox.moe/3cclui.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g9",
      title: "GFX Gold Ship Uma Musume",
      category: "Graphic Design",
      image: "https://files.catbox.moe/h1nicf.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2025",
      aspect: "portrait",
    },
    {
      id: "g10",
      title: "Poster iPhone 14 Pro Max",
      category: "Graphic Design",
      image: "https://files.catbox.moe/es69mz.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2023",
      aspect: "portrait",
    },
    {
      id: "g11",
      title: "Desain Ui UX Yoimiya Genshin Impact",
      category: "Graphic Design",
      image: "https://files.catbox.moe/tzm24m.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2024",
      aspect: "landscape",
    },
    {
      id: "g12",
      title: "Mentahan/GFX 3D Hu-Tao & Freya",
      category: "Graphic Design",
      image: "https://files.catbox.moe/zwrq20.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g13",
      title: "Desain Jajan Soesky Portrait",
      category: "Graphic Design",
      image: "https://files.catbox.moe/qjby62.jpeg",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g14",
      title: "Desain Jajan Pastell!n Portrait",
      category: "Graphic Design",
      image: "https://files.catbox.moe/nkn2hq.jpeg",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "portrait",
    },
    {
      id: "g15",
      title: "Card E-Money Rasfalz Edition",
      category: "Graphic Design",
      image: "https://files.catbox.moe/64hrp4.png",
      creator: "Rasfalz Studio",
      date: "Tahun 2026",
      aspect: "Landscape",
    },
    {
      id: "g16",
      title: "Fotografi Tecno Camon 20 Pro",
      category: "Fotografi",
      image: "https://files.catbox.moe/ys5ghk.jpg",
      creator: "Rasfalz Studio",
      date: "Tahun 2024",
      aspect: "landscape",
    },
    {
      id: "g17",
      title: "Fotografi Tanaman",
      category: "Fotografi",
      image: "https://files.catbox.moe/pd7mk9.JPG",
      creator: "Rasfalz Studio",
      date: "Tahun 2024",
      aspect: "portrait",
    },
    {
      id: "g18",
      title: "Fotografi Surabaya",
      category: "Fotografi",
      image: "https://files.catbox.moe/mqdy07.jpg",
      creator: "Rasfalz Studio",
      date: "Tahun 2024",
      aspect: "portrait",
    },
  ],

  // --- VISUAL IDENTITY DOCUMENTS ---
  visualIdentityDocs: [
    {
      id: "doc-1",
      name: "Rasfalz Studio Master Brand Guidelines",
      type: "PDF Document",
      size: "45.7 MB",
      updated: "31 Agustus 2025",
      description: "Panduan lengkap penggunaan logo, clearspace, tone of voice, filosofi brand, dan standardisasi aset digital.",
      previewImg: "https://files.catbox.moe/zsxle1.png",
      downloadUrl: "https://drive.google.com/file/d/16szI7WSAAPR_lnZn_fUySpi2kC-VxqrO/view?usp=drive_link",
    },
  ],

  // --- PLAYLIST MUSIK BACKGROUND & MUSIC PLAYER ---
  playlist: [
    {
      id: "m1",
      title: "Kita Usahakan Rumah Itu",
      artist: "Sal Priadi",
      album: "Rasfalz Studio Picks",
      duration: "4:05",
      cover: "https://i.ytimg.com/vi/m-KsjaTEHwA/hqdefault.jpg",
      youtubeId: "m-KsjaTEHwA",
    },
    {
      id: "m2",
      title: "Nina - Feast",
      artist: "Feast",
      album: "Rasfalz Studio Picks",
      duration: "4:43",
      cover: "https://i.ytimg.com/vi/iQo-8wx0l0Y/hqdefault.jpg",
      youtubeId: "iQo-8wx0l0Y",
    },
    {
      id: "m3",
      title: "Kita Ke Sana - Hindia",
      artist: "Hindia",
      album: "Rasfalz Studio Picks",
      duration: "4:43",
      cover: "https://i.ytimg.com/vi/DrulgpXAGCA/hqdefault.jpg",
      youtubeId: "DrulgpXAGCA",
    },
    {
      id: "m4",
      title: "Membasuh - Hindia feat Rara Sekar",
      artist: "Hindia feat Rara Sekar",
      album: "Rasfalz Studio Picks",
      duration: "6:14",
      cover: "https://i.ytimg.com/vi/0FiJfOviW4U/hqdefault.jpg",
      youtubeId: "0FiJfOviW4U",
    },
    {
      id: "m5",
      title: "Monokrom - Tulus",
      artist: "Tulus",
      album: "Rasfalz Studio Picks",
      duration: "3:39",
      cover: "https://i.ytimg.com/vi/QqJ-Vp8mvbk/hqdefault.jpg",
      youtubeId: "QqJ-Vp8mvbk",
    },
    {
      id: "m6",
      title: "Bergema sampai selamanya - Nadhif Basalamah",
      artist: "Nadhif Basalamah",
      album: "Rasfalz Studio Picks",
      duration: "3:19",
      cover: "https://i.ytimg.com/vi/gvunApwKIiY/hqdefault.jpg",
      youtubeId: "gvunApwKIiY",
    },
    {
      id: "m7",
      title: "Kota ini tak sama tanpamu - Nadhif Basalamah",
      artist: "Nadhif Basalamah",
      album: "Rasfalz Studio Picks",
      duration: "4:33",
      cover: "https://i.ytimg.com/vi/grp6FCnioMM/hqdefault.jpg",
      youtubeId: "grp6FCnioMM",
    },
    {
      id: "m8",
      title: "Penjaga hati - Nadhif Basalamah",
      artist: "Nadhif Basalamah",
      album: "Rasfalz Studio Picks",
      duration: "4:58",
      cover: "https://i.ytimg.com/vi/jia3fhBQ8qI/hqdefault.jpg",
      youtubeId: "jia3fhBQ8qI",
    },
    {
      id: "m9",
      title: "Foto Kita Blur - Nadhif Basalamah",
      artist: "Nadhif Basalamah",
      album: "Rasfalz Studio Picks",
      duration: "4:55",
      cover: "https://i.ytimg.com/vi/ytMxh-_6EcI/hqdefault.jpg",
      youtubeId: "ytMxh-_6EcI",
    },
    {
      id: "m10",
      title: "Rewrite The Stars - Anne-Marie feat. James Arthur",
      artist: "Anne-Marie feat. James Arthur",
      album: "Rasfalz Studio Picks",
      duration: "3:48",
      cover: "https://i.ytimg.com/vi/pRfmrE0ToTo/hqdefault.jpg",
      youtubeId: "pRfmrE0ToTo",
    },
    {
      id: "m11",
      title: "Bersenja Gurau - Raim Laode",
      artist: "Raim Laode",
      album: "Rasfalz Studio Picks",
      duration: "3:28",
      cover: "https://i.ytimg.com/vi/jmvX6XyvCy0/hqdefault.jpg",
      youtubeId: "jmvX6XyvCy0",
    },
    {
      id: "m12",
      title: "Iqro - Raim Laode",
      artist: "Raim Laode",
      album: "Rasfalz Studio Picks",
      duration: "3:54",
      cover: "https://i.ytimg.com/vi/M7oZR-MTEZs/hqdefault.jpg",
      youtubeId: "M7oZR-MTEZs",
    },
    {
      id: "m13",
      title: "everything u are - Hindia",
      artist: "Hindia",
      album: "Rasfalz Studio Picks",
      duration: "3:57",
      cover: "https://i.ytimg.com/vi/lB8ASupNtlw/hqdefault.jpg",
      youtubeId: "lB8ASupNtlw",
    },
    {
      id: "m14",
      title: "Rumah Ke Rumah - Hindia",
      artist: "Hindia",
      album: "Rasfalz Studio Picks",
      duration: "4:38",
      cover: "https://i.ytimg.com/vi/pjhOjHDX0A8/hqdefault.jpg",
      youtubeId: "pjhOjHDX0A8",
    },
    {
      id: "m15",
      title: "Teh Hijau - Tulus",
      artist: "Tulus",
      album: "Rasfalz Studio Picks",
      duration: "3:30",
      cover: "https://i.ytimg.com/vi/RO75uUZiAw0/hqdefault.jpg",
      youtubeId: "RO75uUZiAw0",
    },
    {
      id: "m16",
      title: "Dunia Yang Nanti - Raim Laode",
      artist: "Raim Laode",
      album: "Rasfalz Studio Picks",
      duration: "3:21",
      cover: "https://i.ytimg.com/vi/awWKxGftWh4/hqdefault.jpg",
      youtubeId: "awWKxGftWh4",
    },
  ],

  // --- SKILLS & TOOLS ---
  skills: [
    { name: "Alight Motion", level: 95, category: "Video & Motion", icon: "Film" },
    { name: "CapCut Pro", level: 80, category: "Video & Motion", icon: "Image" },
    { name: "Canva Pro", level: 80, category: "Graphic & Design", icon: "Image" },
    { name: "Figma & Design Systems", level: 80, category: "UI/UX & Product", icon: "Layout" },
    { name: "Blender 3D", level: 70, category: "3D & Render", icon: "Box" },
    { name: "Adobe Photoshop", level: 80, category: "Graphic & Design", icon: "Image" },
    { name: "Adobe Illustrator", level: 80, category: "Graphic & Design", icon: "Image" },
    { name: "Corel Draw", level: 90, category: "Graphic & Design", icon: "Image" },
    { name: "Adobe After Effect", level: 65, category: "Video & Motion", icon: "Film" },
  ],

  // --- RIWAYAT PENGALAMAN & CREATIVE JOURNEY TIMELINE ---
  creativeJourney: [
    {
      year: "2023 - Sekarang",
      role: "Freelance Graphic Designer, Motion Graphic, & Video Editor",
      company: "Independent Creator",
      desc: "Mengerjakan visual identity, desain grafis, animasi grafis, video editing, dan branding assets untuk klien digital.",
      badgeColor: "badge-orange",
    },
    {
      year: "Sep 2025 - Des 2025",
      role: "Graphic Designer",
      company: "Media Print Digital Printing",
      desc: "Mengerjakan desain grafis, banner/spanduk, dan poster untuk kebutuhan klien.",
      badgeColor: "badge-orange",
    },
    {
      year: "Jan 2025 - Apr 2025",
      role: "Graphic Designer & Content Creator",
      company: "Be Smart Digital Marketing",
      desc: "Membuat desain grafis, poster dan video untuk kebutuhan klien dan agensi.",
      badgeColor: "badge-blue",
    },
  ],

  // --- WHAT I DO CARDS (4 Creative Pillars) ---
  whatIDo: [
    {
      title: "Video Editing & Motion Graphics",
      description: "Membuat video Jedag Jedug 3D/Foto, Motion Graphics, AMV, PMV, Typography, dan video promosi komersial dengan pacing sinematik serta sound design kelas atas.",
      icon: "Film",
      accent: "#FF9C0F",
      tags: ["Jedag-Jedug 3D", "Motion Graphics", "AMV / PMV", "Sound Design"],
    },
    {
      title: "Desain Grafis & GFX Anime",
      description: "Mendesain identitas brand, logo, typography art, poster anime (GFX), banner digital, serta manipulasi foto berkualitas tinggi.",
      icon: "Image",
      accent: "#0052F5",
      tags: ["GFX Anime Poster", "Visual Identity", "Digital Art"],
    },
    {
      title: "3D Visuals & Digital Artworks",
      description: "Pemodelan aset 3D, scene environment, pencahayaan sinematik Blender 3D, dan integrasi elemen visual render untuk komposisi video.",
      icon: "Box",
      accent: "#10B981",
      tags: ["Blender 3D", "Render Art", "Visual Assets"],
    },
    {
      title: "Creative Tools & Studio OS",
      description: "Merancang ekosistem portofolio digital berbasis OS interaktif, preset editing visual, dan toolset produktivitas untuk kreator digital.",
      icon: "Sparkles",
      accent: "#8B5CF6",
      tags: ["Editing Presets", "Workflow Tools"],
    },
  ],

  // --- BERITA & PENGUMUMAN (News & Promo Updates) ---
  newsItems: [
    {
      id: "news-1",
      title: "Update Fitur Terbaru: Game Hub, Prediksi Cuaca & Widget Musik Desktop",
      summary: "Rasfalz Studio menghadirkan Game Hub interaktif, prakiraan cuaca live, dan widget musik desktop terpadu.",
      content: `Kabar gembira untuk para pengunjung website Rasfalz Studio! 

Kami dengan bangga mengumumkan pembaruan besar OS v2.0 yang kini telah hadir dengan berbagai fitur baru yang revolusioner:

Fitur Baru di Rasfalz Studio OS v2.0:
• Arcade Gaming Hub: Mainkan game klasik langsung dari desktop! Tersedia Tic-Tac-Toe (vs AI Pintar & 2 Player) dan Snake Arcade dengan papan skor lokal.
• Prediksi Cuaca Live: Widget Jam kini menampilkan prakiraan cuaca real-time dengan informasi suhu, kelembaban, angin, dan ikon visual.
• Widget Musik Desktop: Putar lagu favorit langsung dari desktop dengan kontrol lengkap dan visualisasi audio.
• Sistem Notifikasi: Notifikasi kini muncul di taskbar (Windows) dan status bar (Android) dengan suara ikonik.
• Floating Sidebar: Opsi tampilan sidebar mengambang untuk estetika desktop modern.
• Fitur Kamera, File Explorer, & Gallery : Camera, File Explorer, dan Gallery kini telah tersedia untuk digunakan.
• Fitur Visual Identity : Logo, Icon, Desktop Background, dll.
• Fitur Premium Apps dan Commision : Tersedia fitur pemesanan akun premium aplikasi dan jasa komisioning.
• Akses Mudah : Akses mudah ke seluruh fitur dan konten dengan navigasi yang intuitif.

Rasfalz Studio OS kini lebih interaktif, fungsional, dan personal dari sebelumnya.`,
      category: "Update",
      badge: "New Features",
      badgeType: "blue",
      isLatest: false,
      date: "4 September 2026",
      readTime: "Tak Terhingga",
      image: "https://files.catbox.moe/a415ml.png",
    },
    {
      id: "news-2",
      title: "Selamat Datang di website Rasfalz Studio yang baru!",
      summary: "Rasfalz Studio kini memiliki website baru yang lebih lengkap dan user-friendly.",
      content: `Kabar gembira untuk para pengunjung website Rasfalz Studio!

Selamat datang di website Rasfalz Studio yang baru! 
Kami sangat antusias untuk terus menyajikan konten dan layanan berkualitas kepada Anda dengan pengalaman yang lebih baik. 

Website yang baru ini akan memiliki fitur-fitur yang lebih lengkap dan user-friendly dibandingkan sebelumnya, serta akan lebih mudah diakses oleh para pengunjung.
Maka dari itu, silahkan kunjungi website kami dan nikmati fitur-fitur baru yang telah kami sediakan.

Terima kasih atas dukungannya yang tak ternilai bagi Rasfalz Studio!`,
      category: "News",
      badge: "Welcome!!",
      badgeType: "blue",
      isLatest: false,
      date: "4 September 2026",
      readTime: "Tak Terhingga",
      image: "https://files.catbox.moe/kftuz1.png",
    },
    {
      id: "news-3",
      title: "Promo Spesial Akun Premium!",
      summary: "Dapatkan Diskon Hingga 70% Untuk Akun Premium Aplikasi Editing Favorit Anda!",
      content: `Kabar gembira untuk para editor dan kreator! 🎉

Dalam rangka memeriahkan suasana, Rasfalz Studio mempersembahkan Promo Spesial Akun Premium! Nikmati akses penuh ke fitur-fitur profesional dengan harga yang jauh lebih hemat. Jangan lewatkan kesempatan emas ini untuk upgrade alat tempur Anda!

Katalog Promo Aplikasi Premium:
• Alight Motion Premium 1 Tahun: Mulai Rp 6.000 (Unlock Semua Efek & No Watermark)
• CapCut Pro Private: Rp 30.000 / bulan (Fitur AI & Ekspor 4K)
• Canva Pro Member: Rp 10.000 / tahun (Akses 1000+ Aset Eksklusif)
• Ibis Paint X Full Unlocked: Rp 15.000 / tahun (Bebas Iklan & Kuas Terbuka)

Semua akun terjamin aman dan bergaransi penuh. Cek menu Premium Apps untuk memesan!`,
      category: "Promo",
      badge: "🏷️ Promo Spesial",
      badgeType: "orange",
      isLatest: false,
      date: "5 September 2026",
      readTime: "Tak Terhingga",
      image: "https://files.catbox.moe/v8da2c.png",
    },
    {
      id: "news-4",
      title: "Promo Spesial Commision & Paid Editing!",
      summary: "Dapatkan Diskon Hingga 70% Untuk Commision & Paid Editing!",
      content: `Kabar gembira untuk para editor dan kreator! 🎉

Dalam rangka memeriahkan suasana, Rasfalz Studio mempersembahkan Promo Spesial Commision & Paid Editing! Nikmati akses penuh ke fitur-fitur profesional dengan harga yang jauh lebih hemat. Jangan lewatkan kesempatan emas ini untuk upgrade alat tempur Anda!

Katalog Promo Commision & Paid Editing:
- Graphic Design & Art Editing: Rp 15.000 / foto
- Motion Graphic & Animation Editing: Rp 35.000 / video
- Video Education & Tugas Sekolah: Rp 20.000 / menit

Semua akun terjamin aman dan bergaransi penuh. Cek menu Commission & Paid Editing untuk memesan!`,
      category: "Promo",
      badge: "🏷️ Promo Spesial",
      badgeType: "blue",
      isLatest: false,
      date: "5 September 2026",
      readTime: "Tak Terhingga",
      image: "https://files.catbox.moe/v8da2c.png",
    },
    {
      id: "news-5",
      title: "Paid Edit/Commision Editing Telah dibuka",
      summary: "Layanan Commision Editing & Paid Edit telah dibuka",
      content: `Pengumuman Penting untuk para Pelanggan dan Pengunjung Rasfalz Studio,  
Layanan Commision Editing & Paid Edit telah dibuka (Tergantung Mood Admin).  
Untuk informasi lebih lanjut, silahkan kunjungi menu Commission untuk memesan. Terima kasih atas pengertiannya.`,
      category: "News",
      badge: "✨ Dibuka",
      badgeType: "green",
      isLatest: true,
      date: "12 September 2026",
      readTime: "Tak Terhingga",
      image: "https://files.catbox.moe/kftuz1.png",
    },
  ],

  // --- GOOGLE DRIVE FOLDERS (FILE EXPLORER) ---
  // Sesuaikan nama, tanggal pembuatan/modified (updated), jumlah file (fileCount), dan tautan (driveUrl) dengan Google Drive Anda:
  googleDriveFolders: [
    {
      id: "fd-portofolio-besmart",
      name: "Portofolio Magang Be Smart",
      category: "Portofolio",
      subtitle: "Portofolio Magang Be Smart",
      description:
        "Kumpulan portofolio selama magang di PT. Be Smart Indonesia",
      fileCount: "50+ File",
      updated: "16 April 2025",
      tags: ["Portofolio", "Be Smart"],
      color: "#FF9C0F",
      preview: "https://files.catbox.moe/9rpwoo.png",
      driveUrl: "https://drive.google.com/drive/folders/1PTmhC2xkY2-ko5QHc-1h8xJq1newHFYE?usp=sharing",
      icon: "Briefcase",
    },
    {
      id: "fd-portofolio-mediaprint",
      name: "Portofolio Media Print",
      category: "Portofolio",
      subtitle: "Portofolio Media Print",
      description:
        "Kumpulan portofolio selama magang di PT. Media Print",
      fileCount: "50+ File",
      updated: "2 Desember 2025",
      tags: ["Portofolio", "Media Print"],
      color: "#10B981",
      preview: "https://files.catbox.moe/og8eal.png",
      driveUrl: "https://drive.google.com/drive/folders/1vwDZYadkaY77k5lCqlebsQrP7awvQlfJ?usp=sharing",
      icon: "Briefcase",
    },
    {
      id: "fd-document",
      name: "Dokumen Tugas Sekolah",
      category: "Dokumen",
      subtitle: "Dokumen Tugas Sekolah",
      description:
        "Folder berisi dokumen tugas sekolah",
      fileCount: "3 File",
      updated: "5 September 2026",
      tags: ["Dokumen", "Tugas Sekolah"],
      color: "#FF5E3A",
      preview: "https://files.catbox.moe/73355w.png",
      driveUrl: "https://drive.google.com/drive/folders/1nUFLXJdmAPiwzd_aBJTJ0N-mLRP8qz_2?usp=sharing",
      icon: "FileText",
    },
    {
      id: "fd-brand",
      name: "Desain Soesky! dan Pastel!n.",
      category: "Desain",
      subtitle: "Kumpulan desain Soesky! dan Pastel!n.",
      description:
        "Kumpulan desain Soesky! dan Pastel!n.",
      fileCount: "10+ File",
      updated: "22 Januari 2026",
      tags: ["Desain", "Soesky!", "Pastel!n."],
      color: "#0052F5",
      preview: "https://files.catbox.moe/9rpwoo.png",
      driveUrl: "https://drive.google.com/drive/folders/16mKNd2rtsZgYlq_MhXSTExOvcK4Xde1-?usp=sharing",
      icon: "Palette",
    },
    {
      id: "fd-fotografi",
      name: "Fotografi Camera Sony",
      category: "Fotografi",
      subtitle: "Fotografi Camera Sony",
      description:
        "Fotografi Camera Sony buatan Rasfalz Studio.",
      fileCount: "50+ File",
      updated: "06 September 2026",
      tags: ["Fotografi", "Camera Sony"],
      color: "#00F2FE",
      preview: "https://files.catbox.moe/og8eal.png",
      driveUrl: "https://drive.google.com/drive/folders/1yDqLadvSKBJeWu9oMx-N2LGCuYtLgWcl?usp=sharing",
      icon: "Camera",
    },
    {
      id: "fd-assets",
      name: "Assets Pack",
      category: "Assets Pack",
      subtitle: "Kumpulan aset - aset yang sering digunakan.",
      description:
        "Kumpulan aset - aset yang sering digunakan.",
      fileCount: "1000+ File",
      updated: "5 September 2026",
      tags: ["Assets Pack", "Design System", "Figma", "Tokens", "CSS Variables", "Glassmorphism"],
      color: "#8B5CF6",
      preview: "https://files.catbox.moe/73355w.png",
      driveUrl: "https://simp.ly/p/Z0l2Lm",
      icon: "Archive",
    },
  ],
};

